### ISSUE TITLE
Wrong path in Python setup.py

### ISSUE THREAD

**Issue by dfa327** [underautomation/UniversalRobots#2]
In order to do a fresh install of Python you need to change the setup.py:

from:
data_files=[('underautomation/universal_robots/lib', ['underautomation/lib/UnderAutomation.UniversalRobots.dll'])],

to:
data_files=[('underautomation/universal_robots/lib', ['underautomation/**universal_robots**/lib/UnderAutomation.UniversalRobots.dll'])],

**Comment by Rufus31415** [comment]
Solved in commit 870f8fbba5214a09ac21ba635e39638ad689dd57
