### ISSUE TITLE
Multiline URScript sending

### ISSUE THREAD

**Issue by berkut0** [underautomation/UniversalRobots#3]
Is it possible to send multiline scripts?

This particular example will execute the last command, I have tried different configurations and different delimiters

![изображение](https://user-images.githubusercontent.com/8849896/197775344-9d1a695b-8e0f-4353-b32e-2bb375caabd9.png)

**Comment by Rufus31415** [comment]
Yes, it is possible, but you have to surround your code in a definition:

```cs
var cmd = @"def prg():
  movej([-1.5,-1.5,-2,-0.5,1.8,0],a=1.4, v=1.05, t=0, r=0)
  movej([-1.2,-1.5,-2.1,-0.5,1.8,0],a=1.4, v=1.23, t=0, r=0)
end
";
```
