### ISSUE TITLE
Acces to Features

### ISSUE THREAD

**Issue by berkut0** [underautomation/UniversalRobots#4]
Can I use internal Features, read or write them?

I don't understand at all how to use custom surfaces. I have a suspicion that this is a problem with UR itself and its protocol.

**Comment by Rufus31415** [comment]
The SDK source code is obfuscated, only UnderAutomation has access to it. What's your issue?

**Comment by berkut0** [comment]
"Features" is a strange term from UR robots. It means something like "custom surfaces," but it's just a vector that you can adjust with the calibration process in the UI. I set up such a surface, give it a name, but I can't figure out if I can use it now. I think it's easy to guess why I might need it

**Comment by Rufus31415** [comment]
ok, it's quite tricky, but it's possible to access it with the SDK.
You need 3 features from the SDK:
- SSH allows you to get your *.installation file. See : https://underautomation.com/universal-robots/documentation/sftp-file-handling
- The SDK has a function to decode this installation file and get the definition of the features as XML. You can then edit this XML, recompile the installation file and send it back by SSH. See: https://underautomation.com/universal-robots/documentation/archive-file
- You can then reload the new installation file via Dashboard Server: https://underautomation.com/universal-robots/documentation/remote-commands#load_installation_file

Do not hesitate to contact the support for more information : 
support [at] underautomation.com
